include $(MODULE_CRYPTO)/*.mk
include $(MODULE_CRYPTO)/utils/*.mk

# (CLI) interfáz de linea de comandos para GPG
install-encryption-GnuPG:
	sudo aptitude install gnupg

# (GUI) interfáz de usuario gráfica para GPG
install-encryption-gpa:
	sudo aptitude install gpa

install-encryption-seahorse:
	sudo aptitude install seahorse

install-encryption-paperkey:
	sudo aptitude install paperkey

install-encryption-crypcat:
	sudo aptitude install cryptcat

install-encryption-pgpdump:
	sudo aptitude install pgpdump

# permite ingresar la "frase de paso" (passphrase) de GPG de forma segura
install-encryption-pinentry-curses:
	sudo aptitude install pinentry-curses

# TODO: necesario cuando utilicemos yubikeys
#install-gpg-dependencies:
#	sudo aptitude install scdaemon
