# TODO: doc + extender features a targets
install-monitordisk-duf:
	cd `mktemp -d` \
	&& curl -LO https://github.com/muesli/duf/releases/download/v0.6.2/duf_0.6.2_linux_amd64.deb \
	&& sudo dpkg -i duf_0.6.2_linux_amd64.deb
