version: '3'
services:
  mynodejs:
    build: .
    volumes:
      - .:/usr/src/manu-app
      # - type: bind
      #   source: ./public
      #   target: /usr/src/manu-app/public
      # - type: bind
      #   source: ./node_modules
      #   target: /usr/src/manu-app/node_modules
#      - .:/usr/src/manu-app/node_modules
    ports:
      - 8000:8000
