version: '3.8'
services:
  servidor-http:
    build:
      dockerfile: Dockerfile
      context: .
      # tty: true # docker run -i
      # stdin_open: true # docker run -t
    volumes:
      # TODO: usar variables para reusar entre los Makefiles y Dockerfile
      # forma corta de crear el volumen
      - ./public:/var/www/public
      # ó podemos crear el mismo tipo volumen más detallado
      # - type: bind
      #   source: ./public
      #   target: /var/www/public
    ports:
      - 8000:8000
