CURRENT_DESKTOP_ENVIRONMENT=$${XDG_CURRENT_DESKTOP}

install-gnome-desktop:
	@sudo aptitude install ubuntu-desktop

install-kde-plasma-desktop:
	@sudo aptitude install kubuntu-desktop

install-mate-desktop:
	@sudo aptitude install mate-core

install-cinnamon-desktop:
	@sudo aptitude install cinnamon

install-xfce4-desktop:
	@sudo aptitude install xfce4

install-budgie-desktop:
	@sudo aptitude install budgie-desktop

install-unity-desktop:
	@sudo aptitude install ubuntu-unity-desktop

install-phanteon-desktop:
	@sudo aptitude install elementary-desktop

install-lxqt-desktop:
	@sudo aptitude install lxqt

install-lxde-desktop:
	@sudo aptitude install lubuntu-desktop

install-enlightenment-desktop:
	@add-apt-repository ppa:niko2040/e19 \
	&& aptitude update \
	&& aptitude install enlightenment

## uninstall

# TODO: aptitude remove pkg Vs aptitude remove -purge pkg
remove-ubuntu-desktop:
	@sudo aptitude remove ubuntu-desktop

remove-kubuntu-desktop:
	@sudo aptitude remove kubuntu-desktop

remove-mate-desktop:
	@sudo aptitude remove mate-core

remove-cinnamon-desktop:
	@sudo aptitude remove cinnamon

remove-xfce4-desktop:
	@sudo aptitude remove xfce4

remove-budgie-desktop:
	@sudo aptitude remove budgie-desktop

remove-unity-desktop:
	@sudo aptitude remove ubuntu-unity-desktop

remove-phanteon-desktop:
	@sudo aptitude remove elementary-desktop

remove-lxqt-desktop:
	@sudo aptitude remove lxqt

remove-lxde-desktop:
	@sudo aptitude remove lubuntu-desktop

# remove-enlightenment-desktop:
